### ISSUE TITLE
pre-release repo doesnt work

### ISSUE THREAD

**Issue by LastExceed** [markjsosnowski/BlueMageHelper#11]
i added `https://markjsosnowski.github.io/FFXIV/plugin_repo.json` to my repos and enabled testing versions, but blue mage helper doesn't show up in the isntaller

**Comment by markjsosnowski** [comment]
the official repo should include it soon, it's preferred to just wait until that happens.

**Comment by markjsosnowski** [comment]
plugin should be available from dalamud testing. please continue to report any issues to this github page.
