### ISSUE TITLE
Needs Update 6.0

### ISSUE THREAD

**Issue by DiggityMan420** [markjsosnowski/BlueMageHelper#2]
needs updating to 6.0 if u plan on it

**Comment by markjsosnowski** [comment]
yes, this will be updated once the queues are more forgiving

**Comment by 1111-glitch** [comment]
Hey, the queues don't seem to be as bad now any plans on an update? Not to nag but I love this plugin!

**Comment by IsolatedRainbow** [comment]
The developer and I got together and I believe he submitted the updated plugin to Dalamud just yesterday - Pending approval by the Dalamud Team. If you are so inclined to do a manual install, you should be able to. I don't see the update he threw to Dalamud in here, but I forked it to assist in fixing it and can confirm this works(I'm using in-game now). Obviously, use the release version when it comes out though. 

@markjsosnowski Lemme knows if I can help any more with this :). 

FORKED REPO. USE DALAMUD'S RELEASE VERSION WHEN IT IS MADE AVAILABLE OR USE THE ORIGINAL DEVELOPERS VERSION ONCE UPDATED. This was a quick and dirty fix while just reviewing the code. By no means am I taking credit or ownership of this addon, as OG Dev is making updates to it, simply a couple typo fixes and a simple API update: 
https://github.com/IsolatedRainbow/BlueMageHelper.

**Comment by markjsosnowski** [comment]
api5 version is pending inclusion in dalamud testing.
